name: WebRTC cross-compiling LLVm image build and push

on:
  workflow_dispatch:
    inputs:
      LLVM_VERSION:
        description: 'LLVM version (e.g. 18.1.5)'
        required: true
        default: '18.1.5'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/webrtc/Dockerfile.depot-llvm-cross-arm64
          build-args: |
            LLVM_VERSION=${{ inputs.LLVM_VERSION }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/depot-arm64-cross:llvm-${{ inputs.LLVM_VERSION }}