name: WebRTC library build for arm64

on:
  workflow_dispatch:
    inputs:
      WEBRTC_STABLE:
        description: 'WebRTC branch-head version (e.g. 6422)'
        required: true
        default: '6422'
      LLVM_VERSION:
        description: 'LLVM version (e.g. 18.1.5)'
        required: true
        default: '18.1.5'


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: read  # Needed to pull from GHCR

    steps:
      - name: Free up disk space aggressively
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /opt/hostedtoolcache "$AGENT_TOOLSDIRECTORY"
          df -h

      - uses: actions/checkout@v4

      - name: Authenticate to GHCR
        # we use authorisation as providing the image public is not supported by API, so this is more stable
        # but we try to not forget to make the image public by hand
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run WebRTC build inside prebuilt container
        run: |
          docker run --rm \
            -e LLVM_DIR="/opt/llvm-aarch64" \
            -v ${{ github.workspace }}:/work \
            ghcr.io/${{ github.repository_owner }}/depot-arm64-cross:llvm-${{ inputs.LLVM_VERSION }} \
            bash -c '
              cd /work &&
              mkdir -p /tmp/webrtc &&
              cd /tmp/webrtc &&
              fetch --nohooks webrtc &&
              cd webrtc/src &&
              git fetch origin --tags --prune &&
              git checkout branch-heads/${WEBRTC_STABLE} -b branch_${WEBRTC_STABLE} &&
              gclient sync --with_branch_heads --with_tags &&
              gn gen out/Release --args="is_clang=true target_os=\"linux\" target_cpu=\"arm64\" \\
                is_debug=false\\
                use_sysroot=false\\
                treat_warnings_as_errors=false\\
                enable_iterator_debugging=false\\
                use_custom_libcxx=false\\
                rtc_include_tests=false\\
                rtc_build_examples=false\\
                rtc_build_tools=false\\
                rtc_use_pipewire=false\\
                rtc_enable_protobuf=true\\
                rtc_enable_libevent=false\\
                rtc_use_x11=false\\
                rtc_use_gtk=false\\
                rtc_use_openssl=false\\
                rtc_use_h264=true\\
                rtc_use_builtin_ssl_root_certs=true\\
                clang_base_path=\"${LLVM_DIR}\"" &&
              ninja -C out/Release -j$(nproc)
            '

      - name: Upload WebRTC library
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-${{ inputs.WEBRTC_STABLE }}
          path: /tmp/webrtc/webrtc/src/out/Release/obj/libwebrtc.a