name: WebRTC library build for arm64

on:
  workflow_dispatch:
    inputs:
      WEBRTC_STABLE:
        description: 'WebRTC branch-head version (e.g. 6422)'
        required: true
        default: '6422'
      LLVM_VERSION:
        description: 'LLVM version (e.g. 18.1.5)'
        required: true
        default: '18.1.5'


jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      packages: read  # Needed to pull from GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Run WebRTC build inside prebuilt container
        run: |
          docker run --rm \
            -e LLVM_DIR="/opt/llvm-aarch64" \
            -v ${{ github.workspace }}:/work \
            ghcr.io/${{ github.repository_owner }}/depot-arm64-cross:llvm-${{ inputs.LLVM_VERSION }} \
            bash -c '
              cd /work &&
              mkdir -p /tmp/webrtc &&
              cd /tmp/webrtc &&
              fetch --nohooks webrtc &&
              cd webrtc/src &&
              git fetch origin --tags --prune &&
              git checkout branch-heads/${WEBRTC_STABLE} -b branch_${WEBRTC_STABLE} &&
              gclient sync --with_branch_heads --with_tags &&
              gn gen out/Release --args="is_clang=true target_os=\"linux\" target_cpu=\"arm64\" \\
                is_debug=false\\
                rtc_include_tests=false\\
                rtc_build_examples=false\\
                rtc_build_tools=false\\
                treat_warnings_as_errors=false\\
                use_custom_libcxx=false\\
                clang_base_path=\"${LLVM_DIR}\"" &&
              ninja -C out/Release -j$(nproc)
            '

      - name: Upload WebRTC library
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-${{ inputs.WEBRTC_STABLE }}
          path: /tmp/webrtc/webrtc/src/out/Release/obj/libwebrtc.a